name: flutter_example
description: Example app with DCL setup.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  dart_code_linter: 1.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
