name: dart_code_linter
version: 1.1.2
description: Dart Code Linter is a software analytics tool that helps developers analyse and improve software quality. Dart Code Linter is based on a fork of Dart Code Metrics.
repository: https://github.com/bancolombia/dart-code-linter

environment:
  sdk: ">=3.0.0 <4.0.0"

platforms:
  linux:
  windows:
  macos:

dependencies:
  analyzer: ^6.4.1
  analyzer_plugin: ^0.11.3
  ansicolor: ^2.0.2
  args: ^2.5.0
  collection: ^1.18.0
  crypto: ^3.0.3
  file: ^7.0.0
  glob: ^2.1.2
  html: ^0.15.4
  http: ^1.2.1
#  meta: ^1.14.0
  path: ^1.9.0
  platform: ^3.1.4
  pub_updater: ^0.4.0
  source_span: ^1.10.0
  uuid: ^4.4.0
  xml: ">=5.3.0 <7.0.0"
  yaml: ^3.1.2

dev_dependencies:
  coverage: ^1.7.2
  intl: ^0.19.0
  lints: ^3.0.0
  mocktail: ^1.0.3
  test: ^1.25.3

  # internal package, used only in tests data
  test_lints:
    path: ./test/resources/test_lints

executables:
  metrics:
